all:
  vars:
    ansible_connection: network_cli
    ansible_network_os: cisco.ios.ios
    ansible_user: user
    ansible_password: "P@ssw0rd"
    ansible_become: true
    ansible_become_method: enable
    ansible_become_password: "P@ssw0rd"
  children:
    ios_routers:
      hosts:
        rtr-binus-anggrek:
          ansible_host: 192.168.10.10
        rtr-binus-alsut:
          ansible_host: 192.168.10.20
        rtr-binus-inter:
          ansible_host: 192.168.10.30
